Repository hassanannajjar/common_ui_toolkit, pull requests merged in 2021-08, with the labels that each got.

#14 touchable opacity
  example/lib/main.dart
  lib/components/common_container/CommonContainer.dart
  lib/components/common_text/CommonText.dart
  lib/components/common_text/CommonTextTree.dart
  lib/components/index.dart
  lib/components/touchable_opacity/TouchableOpacity.dart
  lib/components/touchable_opacity/index.dart
  lib/models/CommonTextModel.dart
  lib/utils/Constants.dart
  lib/utils/Helper.dart
Labels: component, Done

#16 Add common touchable
  lib/components/common_container/CommonContainer.dart
  lib/components/common_touchable/CommonTouchable.dart
  lib/components/common_touchable/index.dart
  lib/components/index.dart
  lib/components/touchable_opacity/TouchableOpacity.dart
  lib/components/touchable_opacity/index.dart
  lib/models/CommonContainerModel.dart
  lib/models/CommonTextModel.dart
  lib/utils/Helper.dart
Labels: component, To Test

#17 Add withTapEffect and not null check
  example/lib/main.dart
  lib/components/common_container/CommonContainer.dart
  lib/components/common_text/CommonTextTree.dart
  lib/components/common_touchable/CommonTouchable.dart
  lib/components/common_touchable/TouchableEffect.dart
  lib/components/common_touchable/index.dart
  lib/models/CommonContainerModel.dart
  lib/models/CommonTextModel.dart
Labels: bug, component, To Test

#15 added Drawer and example screens
  CHANGELOG.md
  example/lib/main.dart
  example/lib/screens/Containers.dart
  example/lib/screens/Drawer.dart
  example/lib/screens/Texts.dart
  example/lib/screens/index.dart
  example/lib/utils/Constants.dart
  example/pubspec.lock
  lib/components/common_container/CommonContainer.dart
  lib/components/common_touchable/CommonTouchable.dart
  lib/components/common_touchable/TouchableEffect.dart
  lib/models/CommonContainerModel.dart
  lib/utils/Constants.dart
  pubspec.yaml
Labels: component, example, doing

#18 Fix touchable text bug
  lib/components/common_text/CommonTextTree.dart
  lib/components/common_touchable/CommonTouchable.dart
Labels: bug, component, To Test

#19 Update texts screen
  CHANGELOG.md
  example/lib/main.dart
  example/lib/screens/Containers.dart
  example/lib/screens/Texts.dart
  example/pubspec.lock
  lib/components/common_container/CommonContainer.dart
  lib/components/common_touchable/CommonTouchable.dart
  lib/components/common_touchable/TouchableEffect.dart
  lib/models/CommonContainerModel.dart
  pubspec.yaml
Labels: component, example, Done
